const $=s=>document.querySelector(s), canvas=$('#canvas'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const art={ruins:new Image(),ruinsDoor:new Image(),home:new Image(),homeAfter:new Image(),grocery:new Image(),clinic:new Image(),school:new Image(),shelter:new Image(),square:new Image(),act7Square:new Image(),finalRoom:new Image(),fred:new Image(),walk:new Image(),elderRocker:new Image()};art.ruins.src='assets/fred-ruins-bg.png';art.ruinsDoor.src='assets/fred-ruins-door-bg-v1.png';art.home.src='assets/fred-home-interior-bg-v1.png';art.homeAfter.src='assets/fred-home-interior-postbomb-v1.png';art.grocery.src='assets/fred-grocery-shop-bg-v1.png';art.clinic.src='assets/fred-field-clinic-bg-v1.png';art.school.src='assets/fred-school-bg-v1.png';art.shelter.src='assets/fred-shelter-bg-v1.png';art.square.src='assets/fred-square-bg-v1.png';art.act7Square.src='assets/fred-act7-square-bg-v2.png';art.finalRoom.src='assets/fred-final-living-room-bg-v1.png';art.fred.src='assets/fred-character-sheet.png';art.walk.src='assets/fred-walk-sheet-v2.png';art.elderRocker.src='assets/elder-fred-rocker-upholstered-v1.png';
const ui={title:$('#titleScreen'),monologue:$('#monologue'),monologueText:$('#monologueText'),filmCredits:$('#filmCredits'),filmCreditsRoll:$('#filmCreditsRoll'),memoryTransition:$('#memoryTransition'),dialogue:$('#dialogue'),speaker:$('#speaker'),line:$('#line'),choice:$('#choice'),question:$('#question'),options:$('#options'),puzzle:$('#puzzle'),parts:$('#parts'),tuning:$('#tuning'),freq:$('#frequency'),prompt:$('#prompt'),scene:$('#sceneLabel'),clarity:$('#clarity')};
let game={started:false,scene:0,x:105,y:410,dir:1,mist:0,clarity:3,locked:true,event:0,mirrorState:0,boss:false,bossT:0,loops:0,ending:false,endingRoom:false,keys:{},debris:[],falling:[],flash:0,interact:null,shake:0,wobble:0,fade:0,fadeDir:0,plane:0,planeImpact:false,impact:[],sceneIntro:0};
const dust=Array.from({length:42},(_,i)=>({x:(i*137)%960,y:(i*83)%430+40,r:i%3+1,s:.15+(i%5)/18}));
const ashField=$('#ashField');for(let i=0;i<72;i++){let flake=document.createElement('i');flake.style.setProperty('--x',`${Math.random()*100}%`);flake.style.setProperty('--size',`${1+Math.random()*3.5}px`);flake.style.setProperty('--drift',`${(Math.random()-.5)*120}px`);flake.style.setProperty('--dur',`${6+Math.random()*11}s`);flake.style.setProperty('--delay',`${-Math.random()*15}s`);flake.style.setProperty('--opacity',`${.25+Math.random()*.48}`);flake.style.setProperty('--ash',Math.random()>.7?'#d4c5a5':'#8d8b83');ashField.appendChild(flake)}
const scenes=[
 {name:'01 · HOME',bg:['#6e5435','#241b13'],end:850,objects:[[230,'table'],[510,'radio'],[770,'window']]},
 {name:'02 · RESIDENTIAL STREET',bg:['#5e625d','#171a19'],end:860,objects:[[190,'ruin'],[640,'door'],[855,'sign']]},
 {name:'03 · GROCERY SHOP',bg:['#414039','#131514'],end:860,objects:[[440,'bread'],[820,'mirror']]},
 {name:'04 · FIELD CLINIC',bg:['#182027','#050708'],end:860,objects:[[190,'bed'],[366,'clinicTable'],[366,'list'],[460,'lamp'],[690,'bed'],[820,'bed'],[294,'clinicPaperA'],[394,'clinicPaperB'],[742,'clinicPaperC']]},
 {name:'05 · SCHOOL',bg:['#272e33','#090b0d'],end:860,objects:[[230,'desk'],[760,'board']]},
 {name:'06 · SHELTER',bg:['#151b20','#050607'],end:860,objects:[[250,'bed'],[500,'radio'],[760,'tunnel']]},
 {name:'07 · SQUARE',bg:['#111519','#020303'],end:870,objects:[[200,'luggage'],[480,'clock'],[820,'gate']]},
 {name:'08 · MORNING',bg:['#c9baa0','#625e55'],end:900,objects:[]}
];
const questions=[
 ['When the air-raid siren sounds, you hear your mother somewhere beyond the walls.',['Run toward her voice.','Freeze where you stand.','Crawl beneath the table.']],
 ['A voice rises from the ruins once more.',['Answer: “I am here.”','Hold your breath and listen.','Cover your ears.']],
 ['A child is crying for help behind the door.',['Try to help.','Ask who is there.','Tell yourself it is only the wind.']],
 ['You cannot see the aircraft, but their engines are drawing closer.',['Stop and follow the shadow.','Hide in the doorway.','Run forward with your eyes shut.']],
 ['Only one hard crust of bread remains.',['Leave it on the counter.','Eat it now.','Take it, even if you do not need it.']],
 ['An older man is sitting in the mirror.',['That is me, too.','It is only a warped reflection.','That is not me.']],
 ['A note beside an empty bed reads: “If I fall asleep, tell me whether it is safe outside.”',['Not yet, but the sky will brighten.','I do not know.','There is nowhere left that is safe.']],
 ['The list gives two ages at once: “13” and “83.” Do you look closer?',['Wipe away the dust.','Read only the reverse side.','Do not look. Keep moving.']],
 ['After the war ends, people will…',['Learn how to live again.','Struggle toward another life.','Find that the war never truly ends.']],
 ['If I leave, will they believe that I have forgotten?',['Leaving is not the same as forgetting.','Perhaps I should wait one more day.','How could I possibly leave?']],
 ['Through the static, a patient voice says: “Fred, it is morning. Come back to the room.” Which sound do you follow?',['The steady voice in the radio.','Both voices, for one more moment.','The old siren calling from the past.']],
 ['The tunnel answers in your mother’s voice: “Fred, do not leave.”',['I can carry you with me—and still go.','I need one more moment to listen.','I will go back and find you.']],
 ['If the war is over, why are you still running?',['Because if I stop, I will see everything I lost.','Because I no longer know where to go.','Because, for me, the war never really ended.']]
];
const maze={step:0,errors:0,busy:false,path:['forward','left','right','forward'],nodes:[12,8,9,5,6],figures:['◌','♜','♟','⌁'],names:['Empty bed','Old stairwell','Hanging coat','Wind at the exit']};
const clinicFlicker={next:0,level:0};
function clinicLampLevel(){if(!game.clinicLight){clinicFlicker.level=0;clinicFlicker.next=0;return 0}const now=performance.now();if(now>=clinicFlicker.next){const dip=Math.random()<.22;clinicFlicker.level=dip?.12+Math.random()*.28:.82+Math.random()*.18;clinicFlicker.next=now+(dip?28+Math.random()*95:110+Math.random()*430)}return clinicFlicker.level}
const clinicPaperSpots=[{x:294,y:414,w:23,h:12,r:.28,hit:33},{x:394,y:394,w:20,h:11,r:-.22,hit:31},{x:742,y:410,w:22,h:12,r:.16,hit:33}];
const schoolPhotoSpots=[{x:185,y:342,w:22,h:14,r:-.18,hit:33},{x:282,y:250,w:20,h:13,r:.25,hit:31},{x:392,y:286,w:19,h:13,r:-.28,hit:30},{x:476,y:238,w:21,h:13,r:.13,hit:32},{x:538,y:306,w:20,h:12,r:-.22,hit:31},{x:686,y:386,w:22,h:13,r:.29,hit:33}];
let audioContext,lastFootstepAt=0,footstepBeat=0;
function mazeTone(strength){try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();let o=audioContext.createOscillator(),g=audioContext.createGain(),now=audioContext.currentTime;o.type=strength>3?'sine':'sawtooth';o.frequency.setValueAtTime(170+strength*85,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.015+strength*.012,now+.025);g.gain.exponentialRampToValueAtTime(.0001,now+.24);o.connect(g).connect(audioContext.destination);o.start(now);o.stop(now+.26)}catch(e){}}
function footstepTone(){try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();audioContext.resume?.();const now=audioContext.currentTime,beat=footstepBeat++%2,len=.14,buffer=audioContext.createBuffer(1,audioContext.sampleRate*len,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const fade=1-i/data.length;data[i]=(Math.random()*2-1)*fade}const src=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),g=audioContext.createGain();src.buffer=buffer;filter.type='bandpass';filter.frequency.setValueAtTime(beat?1450:1850,now);filter.Q.setValueAtTime(1.1,now);g.gain.setValueAtTime(.0001,now);g.gain.linearRampToValueAtTime(beat?.026:.032,now+.008);g.gain.exponentialRampToValueAtTime(.012,now+.055);g.gain.setValueAtTime(.009,now+.068);g.gain.exponentialRampToValueAtTime(.0001,now+.14);src.connect(filter).connect(g).connect(audioContext.destination);src.start(now);src.stop(now+len)}catch(e){}}
function planePassTone(){try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();audioContext.resume?.();const now=audioContext.currentTime,o=audioContext.createOscillator(),h=audioContext.createOscillator(),g=audioContext.createGain(),hg=audioContext.createGain();o.type='sawtooth';h.type='sine';o.frequency.setValueAtTime(62,now);o.frequency.exponentialRampToValueAtTime(118,now+.65);o.frequency.exponentialRampToValueAtTime(48,now+1.65);h.frequency.setValueAtTime(124,now);h.frequency.exponentialRampToValueAtTime(236,now+.65);h.frequency.exponentialRampToValueAtTime(96,now+1.65);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.035,now+.35);g.gain.exponentialRampToValueAtTime(.0001,now+1.65);hg.gain.setValueAtTime(.0001,now);hg.gain.exponentialRampToValueAtTime(.012,now+.35);hg.gain.exponentialRampToValueAtTime(.0001,now+1.65);o.connect(g).connect(audioContext.destination);h.connect(hg).connect(audioContext.destination);o.start(now);h.start(now);o.stop(now+1.7);h.stop(now+1.7)}catch(e){}}
function setMazeMeter(n){[...document.querySelectorAll('#mazeMeter i')].forEach((bar,i)=>bar.classList.toggle('on',i<n))}
function renderMaze(){let map=$('#mazeMap');map.innerHTML='';for(let i=0;i<16;i++){let cell=document.createElement('i');if(maze.nodes.slice(0,maze.step+1).includes(i))cell.classList.add('visited');if(i===maze.nodes[maze.step])cell.classList.add('current');map.appendChild(cell)}map.classList.toggle('locked',maze.errors===0);$('#mazeStatus').textContent=`TURN ${maze.step+1} / 4${maze.errors?` · ECHOES ${maze.errors}`:''}`;$('#mazeFigure').textContent=maze.figures[maze.step];let box=$('#mazeDirections');box.innerHTML='';[['left','← LEFT'],['forward','↑ FORWARD'],['right','RIGHT →']].forEach(([dir,label])=>{let b=document.createElement('button');b.textContent=label;b.onmouseenter=b.onfocus=()=>previewMaze(dir);b.onclick=()=>chooseMaze(dir);box.appendChild(b)})}
function previewMaze(dir){let strength=dir===maze.path[maze.step]?5:1+((maze.step+dir.length)%2);setMazeMeter(strength);$('#mazeCaption').textContent=strength===5?'The steady voice is strongest there.':'Only the shelter’s old hum returns.';mazeTone(strength)}
function chooseMaze(dir){if(maze.busy)return;maze.busy=true;let correct=dir===maze.path[maze.step];if(correct){maze.step++;game.flash=7;$('#mazeCaption').textContent=maze.step>=4?'The signal is close. Keep following the living voice.':'The voice shifts ahead. Listen again; do not chase the echo.';if(maze.step>=4){setTimeout(()=>{$('#soundMaze').classList.add('hidden');say('BROADCAST','…Fred? Keep walking. You are here. You are safe.',()=>{game.locked=false;startChase()})},700);return}}else{maze.errors++;maze.step=Math.max(0,maze.step-1);game.shake=5;$('#mazeCaption').textContent='The echo circles back. The past is loud, but it is not the way out.'}setTimeout(()=>{maze.busy=false;renderMaze()},650)}
function startSoundMaze(){game.locked=true;maze.step=0;maze.errors=0;maze.busy=false;const dirs=['left','forward','right'];maze.path=[];for(let i=0;i<4;i++){let choices=dirs.filter(d=>d!==maze.path[i-1]);maze.path.push(choices[Math.floor(Math.random()*choices.length)])}$('#soundMaze').classList.remove('hidden');renderMaze();setMazeMeter(0);$('#mazeCaption').textContent='The calm voice moves through the tunnel. Hover over each direction; the strongest hiss points toward the present.';$('#mazeStatus').textContent='TURN 1 / 4 · FOLLOW THE STEADY SIGNAL'}
function reset(){game={started:true,scene:0,x:520,y:410,dir:-1,mist:0,clarity:3,locked:true,introWalk:false,event:0,homeDamaged:false,scene1ContinueHint:false,mirrorState:0,mirrorBusy:false,mirrorTurn:0,reactionType:'',reactionPose:'idle',reactionFx:'',reactionMove:false,reactionMoveTarget:0,crouchBlend:0,clinicPapers:[false,false,false],clinicRecord:false,photoPieces:[false,false,false,false,false,false],photoComplete:false,photoLiftAt:0,photoQuestionTriggered:false,blackboardAnswer:null,blackboardOpen:false,boss:false,bossT:0,loops:0,ending:false,endingRoom:false,keys:{},debris:[],falling:[],flash:0,interact:null,shake:0,wobble:0,fade:0,fadeDir:0,plane:0,planeImpact:false,planeSoundPlayed:false,impact:[],sceneIntro:100};lastFootstepAt=0;footstepBeat=0;ui.title.classList.add('hidden');ui.prompt.classList.add('hidden');ui.memoryTransition.classList.add('hidden');updateHUD();startMonologue(openingMonologue,()=>playMemoryTransition(()=>say('BROADCAST','…This is a temporary broadcast station… Is anyone still alive? …',()=>walkToRadio())));canvas.parentElement.focus()}
function walkToRadio(){game.locked=true;game.introWalk=true;game.x=520;game.dir=-1;ui.prompt.classList.add('hidden')}
function say(s,l,cb){game.locked=true;ui.speaker.textContent=s;ui.line.textContent=l;ui.dialogue.classList.remove('hidden');game.next=()=>{ui.dialogue.classList.add('hidden');game.next=null;if(cb)cb();else game.locked=false}}
const openingMonologue=[
 'I am Fred. I think I am. Maybe I was thirteen years old. It has been a long time.',
 'The siren has started again. It has happened so many times that I no longer remember what silence sounds like.',
 'The war has taken our home, our food, our neighbors—and it keeps taking things even when the guns are quiet.',
 'People are calling and shouting through the smoke. The clinic is full. The school is silent. Every street feels like a place I have already lost.',
 'Something is forcing me to keep walking. If I stop, the sirens return. If I keep moving, perhaps the broadcast will lead me somewhere the war cannot reach.'
];
const endingMonologue=[
 'The war ended long ago, but its aftereffects kept forcing Fred back into the same morning.',
 'The sirens controlled his breath. The voices dragged him through the ruins. The black fog kept him trapped inside a war that had already ended.',
 'But this time, Fred breaks free. The voices fall silent. The fog releases him. The past remains where it belongs—in the past.',
 'The boy in the ruins was the part of Fred still trapped in the war. The old man in the quiet room is the part that survived.',
 'He opens his eyes, hears the morning, and takes a breath without fear.',
 'Fred is not forgetting the war. He is finally free from what it left inside him.',
 'OR DID HE?'
];
const endingCredits=[
 'THE WAR ENDED.\nTHE NUMBERS REMAIN.\nWHAT HAPPENED WILL NOT CHANGE.',
 'WORLD WAR II.\nAN ESTIMATED 55 MILLION PEOPLE DIED WORLDWIDE.',
 'DURING THE HOLOCAUST,\nAS MANY AS 1.5 MILLION JEWISH CHILDREN WERE MURDERED OR DIED UNDER NAZI PERSECUTION.',
 'ABOUT ONE IN FIVE PEOPLE\nWHO HAVE EXPERIENCED WAR OR CONFLICT IN THE PREVIOUS TEN YEARS\nEXPERIENCE A MENTAL HEALTH CONDITION.',
 'A WAR DOES NOT END\nWHEN THE GUNS FALL SILENT.',
 'IT CONTINUES\nIN THE BREATH OF THOSE WHO SURVIVE.',
 'IN THE MEMORIES\nTHAT RETURN WITHOUT WARNING.',
 'IN THE CHILDREN\nWHO LEARN TO FEAR THE SKY.',
 'REMEMBERING\nIS NOT THE SAME AS REMAINING TRAPPED.',
 'PEACE IS NOT THE ABSENCE OF MEMORY.',
 'IT IS THE FREEDOM\nTO LIVE BEYOND IT.',
 'FOR EVERY NUMBER,\nTHERE WAS A NAME.',
 'FOR EVERY NAME,\nA LIFE THAT SHOULD HAVE CONTINUED.',
 'MAY WE REMEMBER—\nAND CHOOSE NOT TO REPEAT IT.'
];
let monologueLines=[],monologueIndex=0,monologueDone=null,monologueAutoAdvanceMs=0,monologueAutoTimer=null;
function clearMonologueAutoTimer(){if(monologueAutoTimer){clearTimeout(monologueAutoTimer);monologueAutoTimer=null}}
function renderMonologue(){clearMonologueAutoTimer();ui.monologueText.textContent=monologueLines[monologueIndex]||'';ui.monologueText.classList.remove('show');void ui.monologueText.offsetWidth;ui.monologueText.classList.add('show');if(monologueAutoAdvanceMs&&monologueIndex===monologueLines.length-1)monologueAutoTimer=setTimeout(advanceMonologue,monologueAutoAdvanceMs)}
function startMonologue(lines,done,autoAdvanceLastMs=0){clearMonologueAutoTimer();monologueLines=lines;monologueIndex=0;monologueDone=done;monologueAutoAdvanceMs=autoAdvanceLastMs;game.locked=true;ui.dialogue.classList.add('hidden');ui.monologue.classList.remove('hidden');renderMonologue()}
function advanceMonologue(){if(ui.monologue.classList.contains('hidden'))return;clearMonologueAutoTimer();if(monologueIndex<monologueLines.length-1){monologueIndex++;renderMonologue();return}ui.monologue.classList.add('hidden');const done=monologueDone;monologueLines=[];monologueDone=null;monologueAutoAdvanceMs=0;if(done)done();else game.locked=false}
ui.monologue.addEventListener('click',advanceMonologue);
function playMemoryTransition(done,label='BROADCAST INCOMING'){const labelEl=ui.memoryTransition.querySelector('p');if(labelEl)labelEl.textContent=label;ui.memoryTransition.classList.remove('hidden');ui.memoryTransition.classList.remove('active');void ui.memoryTransition.offsetWidth;ui.memoryTransition.classList.add('active');setTimeout(()=>{ui.memoryTransition.classList.add('hidden');ui.memoryTransition.classList.remove('active');if(done)done()},1150)}
let endingRoomStartedAt=0,endingRoomDone=null,filmCreditsDone=null,filmCreditsTimer=null;
function startEndingRoomAnimation(done){endingRoomStartedAt=performance.now();endingRoomDone=done;game.ending=true;game.endingRoom=true;game.locked=true;ui.dialogue.classList.add('hidden');ui.memoryTransition.classList.add('hidden');ui.prompt.classList.add('hidden');ui.monologue.classList.add('hidden')}
function finishFilmCredits(){if(filmCreditsTimer){clearTimeout(filmCreditsTimer);filmCreditsTimer=null}ui.filmCredits.classList.add('hidden');ui.filmCreditsRoll.classList.remove('play');const done=filmCreditsDone;filmCreditsDone=null;if(done)done()}
function startFilmCredits(lines,done){filmCreditsDone=done;game.locked=true;ui.monologue.classList.add('hidden');ui.dialogue.classList.add('hidden');ui.memoryTransition.classList.add('hidden');ui.filmCreditsRoll.innerHTML='';lines.forEach(line=>{const p=document.createElement('p');p.textContent=line;ui.filmCreditsRoll.appendChild(p)});ui.filmCredits.classList.remove('hidden');ui.filmCreditsRoll.classList.remove('play');void ui.filmCreditsRoll.offsetWidth;requestAnimationFrame(()=>{const duration=Math.max(28,Math.min(58,(ui.filmCreditsRoll.scrollHeight+window.innerHeight)/24));ui.filmCreditsRoll.style.setProperty('--credits-duration',`${duration}s`);ui.filmCreditsRoll.classList.add('play');filmCreditsTimer=setTimeout(finishFilmCredits,duration*1000+550)})}
function returnToTitle(){clearMonologueAutoTimer();game.started=false;game.ending=false;game.endingRoom=false;endingRoomDone=null;filmCreditsDone=null;if(filmCreditsTimer){clearTimeout(filmCreditsTimer);filmCreditsTimer=null}game.locked=true;game.scene=0;game.boss=false;game.next=null;game.interact=null;game.keys={};['monologue','filmCredits','memoryTransition','dialogue','choice','puzzle','tuning','soundMaze','prompt','assistHint'].forEach(id=>document.querySelector(`#${id}`)?.classList.add('hidden'));ui.title.classList.remove('hidden');updateHUD();canvas.parentElement.focus()}
function firstChoiceReaction(n,done){game.reactionType=n===0?'approach':n===1?'hide':'freeze';game.reactionPose=n===0?'run':n===1?'cover':'crouch';game.reactionFx=n===1?'dark':n===2?'static':'';if(n===0){game.locked=false;game.dir=1;game.x=Math.min(860,game.x+34);game.shake=5;setTimeout(()=>{game.locked=true;game.reactionPose='crouch';game.shake=12;say('Fred','Mum?',()=>{game.reactionPose='idle';game.reactionFx='';done&&done()})},520)}else if(n===1){game.locked=true;game.x=Math.max(45,game.x-22);game.shake=3;setTimeout(()=>say('Fred','Do not come out. Wait until the siren stops…',()=>{game.reactionPose='idle';game.reactionFx='';done&&done()}),430)}else{game.locked=true;game.reactionPose='crouch';game.reactionMove=true;game.reactionMoveTarget=220;game.shake=2;setTimeout(()=>{game.reactionMove=false;game.reactionPose='cover';say('Fred','I cannot hear anything from here…',()=>{game.reactionPose='idle';game.reactionFx='';done&&done()})},1850)}}
function ask(i,cb){game.locked=true;let q=questions[i];ui.question.textContent=q[0];ui.options.innerHTML='';q[1].forEach((o,n)=>{let b=document.createElement('button');b.textContent=`${n+1}. ${o}`;b.onclick=()=>{if(b.disabled)return;[...ui.options.children].forEach(x=>x.disabled=true);b.classList.add('selected');game.mist+=n;updateHUD();setTimeout(()=>{ui.choice.classList.add('hidden');if(i===0)firstChoiceReaction(n,()=>cb&&cb(n));else if(i===1){const replies=['I called back until my throat burned. The ruins returned only my own voice.','No one answered. Only the roar of the fire replied.','I covered my ears, but the fire still spoke through my hands.'];say('Fred',replies[n],()=>cb&&cb(n))}else cb&&cb(n)},650)};ui.options.appendChild(b)});ui.choice.classList.remove('hidden')}
function startPuzzle(){
 ui.puzzle.querySelector('h2').textContent='The radio still has power. Reconnect the wires.';ui.puzzle.querySelector('.puzzle-tag').textContent='DAMAGED RADIO · EMERGENCY CIRCUIT';ui.puzzle.classList.remove('hidden');
 const palette=[['RED','#d06a5d'],['BLUE','#6e93bc'],['YELLOW','#c3a15c'],['GREEN','#709678']];
 const shuffle=a=>a.slice().sort(()=>Math.random()-.5),topColors=shuffle(palette),bottomColors=shuffle(palette);
 const ports=(side,colors)=>colors.map((c,i)=>`<button class="socket" style="--wire-color:${c[1]}" data-side="${side}" data-id="${i}" data-color="${c[0]}" title="${c[0]} terminal" aria-label="${side==='top'?'Top':'Bottom'} ${c[0]} terminal"></button>`).join('');
 ui.parts.innerHTML=`<div class="wire-board"><div class="wire-rail"><label>TOP ROW · POWER TERMINALS</label>${ports('top',topColors)}</div><svg id="wireSvg" class="wire-svg" viewBox="0 0 430 230" preserveAspectRatio="none"></svg><div class="wire-rail bottom"><label>BOTTOM ROW · RADIO INPUTS</label>${ports('bottom',bottomColors)}</div><p id="wireHint" class="wire-hint">The radio survived the blast. Match each color to restore the emergency signal.</p></div>`;
 let selected=null,connections=[],hint=$('#wireHint'),svg=$('#wireSvg');const sockets=[...ui.parts.querySelectorAll('.socket')];
 function finish(){ui.puzzle.classList.add('hidden');ask(0,()=>{game.event=1;say('MOTHER (DISTANT)','Fred—!',()=>{game.locked=false;game.homeDamaged=true;game.shake=30;game.wobble=18;game.flash=20;game.debris=[{x:330,t:70},{x:620,t:135}];game.falling=Array.from({length:28},(_,k)=>({x:22+k*34+Math.random()*28,y:-100-Math.random()*300,vy:1.05+Math.random()*2.1,size:4+Math.random()*10,rot:Math.random()*6,spin:(Math.random()-.5)*.12,type:k%3}))})})}
 function point(btn){let r=btn.getBoundingClientRect(),s=svg.getBoundingClientRect();return{x:(r.left+r.width/2-s.left)/s.width*430,y:(r.top+r.height/2-s.top)/s.height*230}}
 function redraw(){svg.innerHTML='';connections.forEach(c=>{let a=point(c.topBtn),b=point(c.bottomBtn),l=document.createElementNS('http://www.w3.org/2000/svg','line');l.setAttribute('x1',a.x);l.setAttribute('y1',a.y);l.setAttribute('x2',b.x);l.setAttribute('y2',b.y);l.style.stroke=c.good?c.topBtn.style.getPropertyValue('--wire-color'):'#9d5650';l.classList.toggle('good',c.good);l.classList.toggle('bad',!c.good);svg.appendChild(l)})}
 function clickSocket(e){let b=e.currentTarget,side=b.dataset.side;if(side==='top'){if(connections.some(c=>c.topBtn===b)){hint.textContent='This terminal is already connected. Choose another.';return}selected=b;sockets.forEach(x=>x.classList.remove('selected'));b.classList.add('selected');hint.textContent=`${b.dataset.color} terminal selected. Click its matching bottom input.`;return}if(!selected||connections.some(c=>c.bottomBtn===b)){hint.textContent='Select a top terminal first, or choose an empty input.';return}let c={topBtn:selected,bottomBtn:b,good:selected.dataset.color===b.dataset.color};connections.push(c);selected.classList.remove('selected');selected.classList.add('connected');b.classList.add('connected');selected=null;redraw();if(!c.good){hint.textContent='Wrong color. The current only flickers.';game.shake=4;mazeTone(1);setTimeout(()=>{connections=connections.filter(x=>x!==c);c.topBtn.classList.remove('connected');c.bottomBtn.classList.remove('connected');redraw();hint.textContent='The old wire burned out. Try again.'},420)}else{hint.textContent=`${c.topBtn.dataset.color} circuit is stable. Keep wiring.`;mazeTone(5)}if(connections.length===4&&connections.every(x=>x.good))setTimeout(finish,520)}
 sockets.forEach(b=>b.addEventListener('click',clickSocket));
 window.addEventListener('resize',redraw,{once:true});
 const demoTop=topColors[0],demoBottom=bottomColors.find(c=>c[0]!==demoTop[0])||bottomColors[1],matchingBottom=bottomColors.find(c=>c[0]===demoTop[0]);
 const demoConnection={topBtn:sockets.find(b=>b.dataset.side==='top'&&b.dataset.color===demoTop[0]),bottomBtn:sockets.find(b=>b.dataset.side==='bottom'&&b.dataset.color===demoBottom[0]),good:false};
 sockets.forEach(b=>b.disabled=true);connections.push(demoConnection);redraw();game.shake=4;mazeTone(1);hint.textContent='A loose wire sparks. Wrong colors only make noise.';
 setTimeout(()=>{connections=connections.filter(c=>c!==demoConnection);const goodConnection={topBtn:demoConnection.topBtn,bottomBtn:sockets.find(b=>b.dataset.side==='bottom'&&b.dataset.color===matchingBottom[0]),good:true};connections.push(goodConnection);redraw();game.flash=8;mazeTone(5);hint.textContent=`${demoTop[0]} matches ${matchingBottom[0]}. The signal returns.`;setTimeout(()=>{connections=connections.filter(c=>c!==goodConnection);redraw();sockets.forEach(b=>b.disabled=false);hint.textContent='TOP ROW IS POWER. BOTTOM ROW IS RADIO. Match colors to reconnect the signal.'},720)},820);
}
function updateHUD(){ui.scene.textContent=scenes[game.scene].name;ui.clarity.textContent='● '.repeat(game.clarity)+'○ '.repeat(3-game.clarity)}
function nextScene(){if(game.fadeDir)return;game.locked=true;game.interact=null;ui.prompt.classList.add('hidden');game.fadeDir=1}
function sceneArrival(){game.sceneIntro=120;if(game.scene===1){game.plane=-220;game.planeSoundPlayed=false;say('Fred','The house behind me is gone. Two engines rumble somewhere above the smoke.')}if(game.scene===3)say('Fred','This used to be a clinic. Why are all the beds empty?');if(game.scene===4)say('BLACKBOARD','Does peace begin on the day the war ends?',()=>say('FRED','A family photograph lies on the desk. Six torn pieces are scattered through this classroom. I should put it back together.',()=>{game.locked=false}));if(game.scene===5)say('Fred','The radio should be silent. Beneath the static, a calm voice is trying to reach me.',()=>startTuning());if(game.scene===6)say('Fred','There is light beyond the gate. If I can cross the square…')}
function startTuning(){
 game.locked=true;ui.tuning.querySelector('p').textContent='TUNE THROUGH THE STATIC · FIND THE STEADY VOICE';ui.tuning.classList.remove('hidden');
 const target=18+Math.floor(Math.random()*65),tolerance=2,start=target>50?target-24:target+24;
 ui.freq.value=start;ui.tuning.querySelector('small').textContent='STATIC — A DISTANT SIREN BENEATH AN ORDINARY VOICE';
 ui.freq.oninput=()=>{const v=+ui.freq.value,diff=Math.abs(v-target);ui.tuning.querySelector('small').textContent=diff<=tolerance?'…Fred? It is eight o’clock. Your tea has gone cold…':diff<=9?'An ordinary voice is beginning to emerge…':'STATIC — A DISTANT SIREN BENEATH AN ORDINARY VOICE'};
 ui.freq.onchange=()=>{const v=+ui.freq.value;if(Math.abs(v-target)<=tolerance){ui.tuning.classList.add('hidden');ask(10,continueAfterTuning)}};
}
function continueAfterTuning(n){const replies=['The room around me has sounds of its own. I want to hear them.','For a moment, the two voices overlap. I cannot tell where one ends.','The siren swallows the room again. I almost forget there is anything else.'];say('FRED',replies[n],()=>ask(11,n=>{if(n===2){game.x=80;say('FRED','The signal recedes. I am back where the broadcast began.',()=>{game.locked=false;game.event=1})}else{game.locked=false;game.event=1}}))}
function offerInteraction(label,action){game.interact=action;ui.prompt.textContent=`E · ${label}`;ui.prompt.classList.remove('hidden')}
function sceneComplete(s){return s===0?game.event>=2:s===1?game.event>=1:s===2?(game.event&3)===3:s===3?(game.event&3)===3:s===4?game.event>=1:s===5?game.event>=2:false}
function mirrorSequence(){if(game.mirrorBusy)return;game.mirrorBusy=true;game.locked=true;game.mirrorState=1;setTimeout(()=>{game.mirrorState=2;setTimeout(()=>{game.mirrorState=0;game.mirrorBusy=false;game.locked=false},420)},500)}
function blockedExit(){game.x=850;offerInteraction('The way forward is blocked',()=>say('Fred','I have not finished searching this place yet.',()=>{game.locked=false}))}
function sceneEvent(){let s=game.scene;game.interact=null;ui.prompt.classList.add('hidden');if(s===0&&game.x>735&&game.event===1)offerInteraction('Leave through the broken window',()=>{game.event=2;ask(1,()=>nextScene())});else if(s===1&&Math.abs(game.x-640)<75&&game.event===0)offerInteraction('Investigate the wooden door',()=>{game.event=1;ask(2,()=>ask(3,()=>{game.locked=false}))});else if(s===1&&game.x>850){if(sceneComplete(s))nextScene();else blockedExit()}else if(s===2&&Math.abs(game.x-440)<75&&!(game.event&1))offerInteraction('Take the last piece of bread',()=>{game.event|=1;ask(4,()=>{game.locked=false})});else if(s===2&&Math.abs(game.x-820)<75&&!game.mirrorBusy)offerInteraction('Look into the cracked mirror',()=>{game.event|=2;mirrorSequence()});else if(s===2&&game.x>850){if(sceneComplete(s))nextScene();else blockedExit()}else if(s===3&&Math.abs(game.x-460)<75&&!(game.event&1))offerInteraction('Pull the clinic light cord',()=>{game.event|=1;game.clinicLight=1;say('','The cord jerks. A warm-white lamp wakes above the beds.',()=>{game.locked=false})});else if(s===3&&Math.abs(game.x-330)<75&&(game.event&1)&&!(game.event&2))offerInteraction('Read the paper on the bedside table',()=>{game.event|=2;clinicSequence()});else if(s===3&&game.x>850){if(sceneComplete(s))nextScene();else blockedExit()}else if(s===4&&game.x>850){if(sceneComplete(s))nextScene();else blockedExit()}else if(s===5&&game.event===1&&game.x>675)offerInteraction('Open the tunnel sketch and listen',()=>{game.event=2;startSoundMaze()});else if(s===6&&game.x>750&&!game.boss)offerInteraction('Follow the open route across the square',()=>{game.event=1;ask(12,()=>startBoss())})}
function clinicSequence(){
 say('','The paper on the bedside table is coated in dust, yet the ink remains legible.',()=>{
   ask(6,()=>{
     say('Fred','Under the bed, beside the cabinet, by the door… together, the three scraps form the same list.',()=>{
       game.locked=false;
     });
   });
 });
}
function startChase(){
 const shelter=game.scene===5;
 const line=shelter
  ? 'The broadcast fades. The tunnel is quiet now; only your footsteps remain.'
  : 'The broadcast fades. In the sudden silence, the old fear rushes in.';
 say('',line,()=>{
  game.locked=false;
  if(shelter){
   // Act 6 is a listening and navigation sequence, not a boss encounter.
   // Clear any legacy chase state so the player can leave the shelter normally.
   game.boss=false;game.bossT=0;
   ui.prompt.textContent='KEEP MOVING RIGHT · THE EXIT IS AHEAD';
  }else{
   game.boss='chase';game.bossT=-180;
   ui.prompt.textContent='RUN FOR THE EXIT · THE FOG IS GATHERING';
  }
  ui.prompt.classList.remove('hidden');
 })
}
function startBoss(){
 game.locked=true;
 say('','The boards fall away. Beyond the gate, the square opens beneath a pale sky.',()=>
   say('Fred','The smoke is lifting, but the silence feels wrong.',()=>
     say('','A dark shape gathers where the morning should be.',()=>
       say('Fred','If I keep going, there will be no place left to hide.',()=>startBossEncounter())
     )
   )
 );
}
function startBossEncounter(){game.boss='storm';game.bossT=0;game.locked=false;game.x=120;game.shake=14;game.flash=18;for(let i=0;i<7+Math.floor(game.mist/3);i++)game.debris.push({x:120+Math.random()*720,t:50+i*38});const lines={approach:'You kept running toward voices that were no longer there.',hide:'You hid so well that the war followed you inside.',freeze:'You survived by becoming still.'};say('BLACK FOG',lines[game.reactionType]||'You could have saved them.',()=>{game.locked=false})}
function hit(){if(game.flash>0)return;game.clarity--;game.flash=25;game.shake=16;updateHUD();if(game.clarity<=0){game.mist=Math.max(0,game.mist-5);game.clarity=3;game.x=100;game.keys={};updateHUD();say('','The signal returns you to the tunnel entrance. Take a breath—then keep moving.',()=>{game.bossT=-320;ui.prompt.textContent='RUN FOR THE EXIT · YOU HAVE A MOMENT';ui.prompt.classList.remove('hidden');game.locked=false})}}
function drawPixelPerson(x,y,old=false){ctx.save();ctx.translate(Math.round(x),Math.round(y));if(old){ctx.fillStyle='#514a3e';ctx.fillRect(-25,-8,52,44);ctx.fillStyle='#302e29';ctx.fillRect(-18,-34,37,38);ctx.fillStyle='#c0aa84';ctx.fillRect(-10,-52,20,18);ctx.fillStyle='#ded0ae';ctx.fillRect(-9,-55,18,6);ctx.fillStyle='#84765e';ctx.fillRect(-36,31,73,9);ctx.fillStyle='#75674f';ctx.fillRect(-31,40,7,22);ctx.fillRect(26,40,7,22);ctx.fillStyle='#b7a47f';ctx.fillRect(-3,-44,3,3);ctx.fillRect(5,-44,3,3)}else if(art.fred.complete&&art.fred.naturalWidth){let moving=game.keys.ArrowLeft||game.keys.ArrowRight||game.keys.a||game.keys.d,cover=game.flash>4;const idleFrames=[{x:65,y:262,w:198,h:445},{x:364,y:262,w:263,h:445},{x:712,y:262,w:246,h:445},{x:1014,y:385,w:324,h:322},{x:1401,y:264,w:181,h:443}],walkFrames=[{x:36,y:267,w:254,h:448},{x:326,y:267,w:211,h:448},{x:619,y:267,w:188,h:448},{x:886,y:266,w:188,h:449},{x:1125,y:274,w:234,h:441},{x:1395,y:267,w:220,h:448}];let phase=Math.floor(Date.now()/105)%10,walkOrder=[0,1,2,3,4,5,4,3,2,1],source=cover?art.fred:(moving&&art.walk.complete&&art.walk.naturalWidth?art.walk:art.fred),c=cover?idleFrames[4]:(moving&&source===art.walk?walkFrames[walkOrder[phase]]:idleFrames[0]),hOut=112,scale=hOut/c.h,w=c.w*scale,bob=moving&&!cover?[0,.7,1,.7,0,-.7,-1,-.7,0,.7][phase]:0,lean=moving&&!cover?Math.sin(phase*Math.PI/5)*.008:0;ctx.translate(0,bob);ctx.rotate(lean);ctx.scale(game.dir,1);ctx.drawImage(source,c.x,c.y,c.w,c.h,-w/2,-hOut,w,hOut)}else{ctx.scale(game.dir,1);ctx.fillStyle='#c9b58a';ctx.fillRect(-8,-53,16,17);ctx.fillStyle='#2b2d28';ctx.fillRect(-13,-36,26,31);ctx.fillRect(-10,-5,7,25);ctx.fillRect(3,-5,7,25)}ctx.restore()}
function drawSceneArchitecture(s){ctx.save();if(s===0){ctx.fillStyle='#4e3b29';ctx.fillRect(0,115,960,315);ctx.fillStyle='#755b3c';for(let x=0;x<960;x+=64)ctx.fillRect(x,150,2,280);ctx.fillStyle='#181713';ctx.fillRect(690,170,160,170);ctx.fillStyle='#9f8357';ctx.fillRect(702,182,136,146);ctx.fillStyle='#372d20';ctx.fillRect(0,105,960,15);ctx.fillRect(80,100,18,330);ctx.rotate(-.12);ctx.fillRect(490,40,20,450)}else if(s===1){ctx.fillStyle='#262a28';for(let x=-30;x<980;x+=190){let h=190+(x%380===0?50:0);ctx.fillRect(x,430-h,150,h);ctx.fillStyle='#0e1110';for(let wx=x+20;wx<x+130;wx+=42)for(let wy=430-h+35;wy<395;wy+=55)ctx.fillRect(wx,wy,20,29);ctx.fillStyle='#262a28'}}else if(s===2){ctx.fillStyle='#25241f';ctx.fillRect(35,105,890,325);ctx.fillStyle='#121311';ctx.fillRect(70,150,280,260);ctx.fillRect(610,145,260,265);ctx.fillStyle='#5a4e39';ctx.fillRect(350,115,260,38);ctx.fillStyle='#211f1a';for(let y=205;y<405;y+=50)ctx.fillRect(95,y,220,8)}else if(s===3){ctx.fillStyle='#11171b';ctx.fillRect(30,90,900,340);ctx.fillStyle='#272723';for(let x=70;x<870;x+=205){ctx.fillRect(x,330,150,18);ctx.fillRect(x+6,348,6,70)}ctx.strokeStyle='#6d6250';ctx.lineWidth=3;for(let x=245;x<850;x+=205){ctx.beginPath();ctx.moveTo(x,150);ctx.lineTo(x,410);ctx.stroke()}let glow=Math.sin(Date.now()/310)>.35;ctx.fillStyle=glow?'rgba(236,219,174,.09)':'rgba(0,0,0,.18)';ctx.fillRect(0,0,960,430)}else if(s===4){ctx.fillStyle='#18201f';ctx.fillRect(20,80,920,350);ctx.fillStyle='#101816';ctx.fillRect(520,125,330,150);ctx.strokeStyle='#625943';ctx.strokeRect(520,125,330,150);ctx.fillStyle='#3b3930';for(let y=330;y<425;y+=45)for(let x=80;x<820;x+=170){ctx.fillRect(x,y,110,8);ctx.fillRect(x+12,y+8,7,34)}}else if(s===5){ctx.fillStyle='#0c1114';ctx.fillRect(0,80,960,350);ctx.fillStyle='#24201a';for(let y=110;y<420;y+=24)for(let x=(y%48?0:18);x<960;x+=54)ctx.fillRect(x,y,48,3);ctx.fillStyle='#020303';ctx.beginPath();ctx.arc(760,420,115,Math.PI,0);ctx.fillRect(645,420,230,10);ctx.fill()}else if(s===6){ctx.fillStyle='#090c0d';ctx.fillRect(390,95,180,335);ctx.beginPath();ctx.moveTo(370,95);ctx.lineTo(480,20);ctx.lineTo(590,95);ctx.fill();ctx.fillStyle='#222521';ctx.beginPath();ctx.arc(480,160,62,0,7);ctx.fill();ctx.strokeStyle='#a18b63';ctx.lineWidth=4;ctx.beginPath();ctx.arc(480,160,48,0,7);ctx.stroke();ctx.beginPath();ctx.moveTo(480,160);ctx.lineTo(480,126);ctx.moveTo(480,160);ctx.lineTo(510,178);ctx.stroke();ctx.fillStyle='#243029';ctx.fillRect(785,255,125,175)}ctx.restore()}
function drawHe111Shadow(x,y,scale,alpha){
 if(x<-230||x>1190)return;
 ctx.save();ctx.translate(x,y);ctx.rotate(-.12);ctx.scale(scale,scale);
 ctx.fillStyle=`rgba(2,3,3,${alpha})`;ctx.shadowColor=`rgba(2,3,3,${alpha*.8})`;ctx.shadowBlur=16;
 // Long, tapered fuselage: nose to the right, tail to the left.
 ctx.beginPath();ctx.moveTo(-132,0);ctx.lineTo(-104,-8);ctx.lineTo(-35,-14);ctx.lineTo(62,-16);ctx.lineTo(121,-11);ctx.quadraticCurveTo(145,0,121,11);ctx.lineTo(62,16);ctx.lineTo(-35,14);ctx.lineTo(-104,8);ctx.closePath();ctx.fill();
 // He 111's broad, slightly swept low wing.
 ctx.beginPath();ctx.moveTo(66,-13);ctx.lineTo(2,-73);ctx.lineTo(-42,-89);ctx.lineTo(-26,-18);ctx.closePath();ctx.fill();
 ctx.beginPath();ctx.moveTo(66,13);ctx.lineTo(2,73);ctx.lineTo(-42,89);ctx.lineTo(-26,18);ctx.closePath();ctx.fill();
 // Twin engine nacelles under the wing: the most readable feature in a passing shadow.
 ctx.beginPath();ctx.ellipse(24,-43,23,10,0,0,7);ctx.fill();ctx.beginPath();ctx.ellipse(24,43,23,10,0,0,7);ctx.fill();
 // Tailplane and the characteristic twin vertical fins.
 ctx.beginPath();ctx.moveTo(-82,-7);ctx.lineTo(-111,-31);ctx.lineTo(-128,-28);ctx.lineTo(-105,-3);ctx.closePath();ctx.fill();
 ctx.beginPath();ctx.moveTo(-82,7);ctx.lineTo(-111,31);ctx.lineTo(-128,28);ctx.lineTo(-105,3);ctx.closePath();ctx.fill();
 ctx.beginPath();ctx.moveTo(-109,-4);ctx.lineTo(-119,-30);ctx.lineTo(-103,-25);ctx.lineTo(-94,-5);ctx.closePath();ctx.fill();
 ctx.beginPath();ctx.moveTo(-109,4);ctx.lineTo(-119,30);ctx.lineTo(-103,25);ctx.lineTo(-94,5);ctx.closePath();ctx.fill();
 ctx.fillStyle=`rgba(0,0,0,${alpha*.42})`;ctx.fillRect(48,-10,16,20);ctx.fillRect(12,-49,25,11);ctx.fillRect(12,38,25,11);
 ctx.restore();
}
function drawStreetSmoke(){let t=Date.now()/1000;ctx.save();ctx.globalCompositeOperation='multiply';for(let i=0;i<13;i++){let y=350-i*28,sway=Math.sin(t*.55+i*.72)*15+i*1.6,rx=20+i*3.4,ry=18+i*1.7;ctx.fillStyle=`rgba(30,35,33,${.045+i*.004})`;ctx.beginPath();ctx.ellipse(510+sway,y,rx,ry,Math.sin(i+t*.2)*.08,0,7);ctx.fill()}ctx.globalCompositeOperation='source-over';ctx.restore()}
function drawStreetLights(){let t=Date.now()/1000,pulse=.035+Math.sin(t*2.1)*.012+Math.sin(t*5.7)*.006;ctx.save();ctx.globalCompositeOperation='screen';[[171,238,70],[742,214,86]].forEach(([x,y,r])=>{let grad=ctx.createRadialGradient(x,y,2,x,y,r);grad.addColorStop(0,`rgba(232,201,135,${Math.max(.015,pulse)})`);grad.addColorStop(1,'rgba(232,201,135,0)');ctx.fillStyle=grad;ctx.fillRect(x-r,y-r,r*2,r*2)});ctx.fillStyle=`rgba(241,207,133,${Math.max(.02,pulse*.8)})`;ctx.fillRect(727,247,26,38);ctx.restore()}
function drawWoodDoor(x){ctx.save();ctx.translate(x,0);ctx.fillStyle='#151614';ctx.fillRect(-43,274,86,156);ctx.fillStyle='#604936';ctx.fillRect(-34,286,68,144);ctx.fillStyle='#74573d';for(let y=292;y<426;y+=23)ctx.fillRect(-31,y,62,3);ctx.strokeStyle='#36291f';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-28,300);ctx.lineTo(28,352);ctx.moveTo(28,300);ctx.lineTo(-28,352);ctx.stroke();ctx.fillStyle='#9b754d';ctx.fillRect(18,360,7,5);ctx.fillStyle='#1d1915';ctx.fillRect(-43,274,86,8);ctx.restore()}
function drawClinicRecord(){
 ctx.save();
 ctx.fillStyle='rgba(2,3,3,.82)';ctx.fillRect(0,0,960,540);
 const x=142,y=48,w=676,h=438;ctx.translate(x,y);ctx.rotate(-.012);
 const paper=ctx.createLinearGradient(0,0,w,h);paper.addColorStop(0,'#d1c6a8');paper.addColorStop(1,'#9d967e');ctx.fillStyle=paper;ctx.fillRect(0,0,w,h);
 ctx.strokeStyle='#544c3e';ctx.lineWidth=3;ctx.strokeRect(5,5,w-10,h-10);ctx.strokeStyle='#eee2bf44';ctx.lineWidth=1;ctx.strokeRect(14,14,w-28,h-28);
 ctx.fillStyle='#353a35';ctx.font='bold 18px Georgia';ctx.fillText('FIELD CLINIC',28,42);ctx.font='11px Courier New';ctx.fillText('PATIENT INTAKE / RECOVERY WARD',29,62);ctx.fillStyle='#5a5548';ctx.fillRect(28,73,w-56,2);
 ctx.fillStyle='#3b3b34';ctx.font='bold 14px Courier New';ctx.fillText('SUBJECT',32,112);ctx.font='bold 22px Georgia';ctx.fillText('FRED',148,112);
 ctx.font='12px Courier New';ctx.fillStyle='#4b493e';ctx.fillText('AGE:',32,151);ctx.font='bold 19px Georgia';ctx.fillText('83',148,151);ctx.fillText('13',216,151);ctx.strokeStyle='#6f463faa';ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(141,143);ctx.lineTo(188,157);ctx.moveTo(143,158);ctx.lineTo(190,143);ctx.stroke();
 ctx.strokeStyle='#5b574a';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(28,211);ctx.lineTo(w-28,211);ctx.stroke();ctx.fillStyle='#3b3b34';ctx.font='12px Courier New';ctx.fillText('ORIGIN',32,242);ctx.font='bold 17px Georgia';ctx.fillText('SWEDEN',148,242);
 ctx.font='12px Courier New';ctx.fillStyle='#4b493e';ctx.fillText('HEIGHT / WEIGHT',32,282);ctx.fillStyle='#554f43';for(let i=0;i<4;i++)ctx.fillRect(150+i*34,270+(i%2)*4,28,15);
 ctx.fillStyle='#3b3b34';ctx.font='12px Courier New';ctx.fillText('CLINICAL STATUS',32,326);ctx.globalAlpha=.22;ctx.font='bold 16px Georgia';ctx.fillText('PSYCHIATRIC PATIENT',148,326);ctx.globalAlpha=1;ctx.strokeStyle='#6f463faa';ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(143,316);ctx.quadraticCurveTo(204,335,267,316);ctx.moveTo(154,331);ctx.quadraticCurveTo(220,309,306,332);ctx.moveTo(196,313);ctx.lineTo(238,335);ctx.moveTo(252,312);ctx.lineTo(286,333);ctx.stroke();
 ctx.globalAlpha=.65;ctx.fillStyle='#6e6757';ctx.font='10px Courier New';ctx.fillText('ARCHIVE COPY · PARTIALLY RESTORED',32,374);ctx.fillText('DOCUMENT RETAINED AFTER EVACUATION',32,391);ctx.globalAlpha=1;
 ctx.fillStyle='#725348';ctx.globalAlpha=.72;ctx.fillRect(w-180,h-72,132,35);ctx.globalAlpha=1;ctx.fillStyle='#d4c5a4';ctx.font='bold 11px Courier New';ctx.fillText('RESTRICTED',w-166,h-50);
 ctx.fillStyle='#4e493e';ctx.font='11px Courier New';ctx.fillText('CLICK TO CLOSE',w-156,h-22);
 ctx.restore();
}
function clinicPaperClick(e){
 if(!game.started||game.scene!==3)return;
 const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*canvas.width,y=(e.clientY-rect.top)/rect.height*canvas.height;
 if(game.clinicRecord){game.clinicRecord=false;game.locked=false;return}
 if(game.locked)return;
 for(let i=0;i<clinicPaperSpots.length;i++){
   const p=clinicPaperSpots[i],hit=p.hit||p.w;if(Math.abs(x-p.x)<hit*.72&&Math.abs(y-p.y)<hit*.55){
     if(!game.clinicPapers[i]){game.clinicPapers[i]=true;game.flash=5;mazeTone(2);ui.prompt.textContent='PAPER FRAGMENT EXAMINED';ui.prompt.classList.remove('hidden');setTimeout(()=>ui.prompt.classList.add('hidden'),900);if(game.clinicPapers.every(Boolean)){game.clinicRecord=true;game.locked=true;ui.prompt.classList.add('hidden')}}
     return;
   }
 }
}
canvas.addEventListener('click',clinicPaperClick);
function maybeTriggerPhotoAgeQuestion(){
 if(game.photoQuestionTriggered||game.blackboardAnswer===null||!game.photoPieces||game.photoPieces.filter(Boolean).length<3)return false;
 game.photoQuestionTriggered=true;
 game.locked=true;ui.prompt.classList.add('hidden');
 setTimeout(()=>ask(7,n=>{
   if(n===1)say('BACK OF THE LIST','WILL PEACE COME?',()=>{game.keys={};game.locked=false});
   else{game.keys={};game.locked=false}
 }),240);
 return true;
}
function photoReflectionSequence(){
 game.event=1;game.locked=true;ui.prompt.classList.add('hidden');
 say('','A summer field: a tent, wildflowers, and a family at play.',()=>{
   say('','The photograph preserves an afternoon from before the war took their home.',()=>{
     say('Fred','They were smiling. I thought the war had taken even that from me.',()=>{
       game.keys={};game.locked=false;
     });
   });
 });
}
function schoolCanvasClick(e){
 if(!game.started||game.scene!==4)return;
 const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*canvas.width,y=(e.clientY-rect.top)/rect.height*canvas.height;
 if(game.locked)return;
 if(game.blackboardAnswer===null&&x>=685&&x<=940&&y>=48&&y<=260){
   game.blackboardOpen=true;ask(8,n=>{game.blackboardAnswer=n;game.blackboardOpen=false;game.locked=false;ui.prompt.textContent='THE ANSWER REMAINS ON THE BOARD';ui.prompt.classList.remove('hidden');setTimeout(()=>ui.prompt.classList.add('hidden'),1400);maybeTriggerPhotoAgeQuestion()});return;
 }
 for(let i=0;i<schoolPhotoSpots.length;i++){
   const p=schoolPhotoSpots[i],hit=p.hit||p.w;if(Math.abs(x-p.x)<hit*.72&&Math.abs(y-p.y)<hit*.55){
     if(!game.photoPieces[i]){
       game.photoPieces[i]=true;game.flash=4;mazeTone(2);
       ui.prompt.textContent=`PHOTO FRAGMENT ${i+1} / 6 · THE IMAGE GROWS`;ui.prompt.classList.remove('hidden');
       setTimeout(()=>ui.prompt.classList.add('hidden'),700);
       const asked=maybeTriggerPhotoAgeQuestion();
       if(game.photoPieces.every(Boolean)){
         game.photoComplete=true;game.locked=true;ui.prompt.textContent='THE PHOTO REASSEMBLES';ui.prompt.classList.remove('hidden');
         setTimeout(photoReflectionSequence,asked?1450:850);
       }
     }
     return;
   }
 }
}
canvas.addEventListener('click',schoolCanvasClick);
function draw(){ctx.save();if(game.shake>0)ctx.translate((Math.random()-.5)*game.shake,(Math.random()-.5)*game.shake);if(game.wobble>0)ctx.translate(Math.sin(Date.now()/74)*game.wobble,Math.cos(Date.now()/91)*game.wobble*.45);let sc=scenes[game.scene],g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,sc.bg[0]);g.addColorStop(1,sc.bg[1]);ctx.fillStyle=g;ctx.fillRect(-20,-20,1000,580);const postBlastReady=game.scene===0&&game.homeDamaged&&art.homeAfter.complete&&art.homeAfter.naturalWidth,homeReady=game.scene===0&&((!game.homeDamaged&&art.home.complete&&art.home.naturalWidth)||postBlastReady),groceryReady=game.scene===2&&art.grocery.complete&&art.grocery.naturalWidth,clinicReady=game.scene===3&&art.clinic.complete&&art.clinic.naturalWidth,schoolReady=game.scene===4&&art.school.complete&&art.school.naturalWidth,shelterReady=game.scene===5&&art.shelter.complete&&art.shelter.naturalWidth,act7Ready=game.scene===6&&art.act7Square.complete&&art.act7Square.naturalWidth,ruinsArt=art.ruinsDoor.complete&&art.ruinsDoor.naturalWidth?art.ruinsDoor:art.ruins,ruinsReady=game.scene===1&&ruinsArt.complete&&ruinsArt.naturalWidth,paintedBackdrop=homeReady||groceryReady||clinicReady||schoolReady||shelterReady||act7Ready||ruinsReady;if(homeReady){ctx.drawImage(postBlastReady?art.homeAfter:art.home,0,0,1672,941,0,0,960,540);ctx.fillStyle=postBlastReady?'rgba(20,22,22,.19)':'rgba(16,17,15,.16)';ctx.fillRect(0,0,960,540)}else if(ruinsReady){ctx.drawImage(ruinsArt,0,0,1672,941,0,0,960,540);ctx.fillStyle='rgba(29,31,29,.08)';ctx.fillRect(0,0,960,540);drawStreetSmoke();drawStreetLights()}else if(groceryReady){ctx.drawImage(art.grocery,0,0,1672,941,0,0,960,540);ctx.fillStyle='rgba(14,16,14,.12)';ctx.fillRect(0,0,960,540)}else if(clinicReady){ctx.drawImage(art.clinic,0,0,1672,941,0,0,960,540);ctx.fillStyle='rgba(4,8,12,.28)';ctx.fillRect(0,0,960,540)}else if(schoolReady){ctx.drawImage(art.school,0,0,1672,941,0,0,960,540);ctx.fillStyle='rgba(8,12,15,.17)';ctx.fillRect(0,0,960,540)}else if(shelterReady){ctx.drawImage(art.shelter,0,0,1672,941,0,0,960,540);ctx.fillStyle='rgba(3,7,9,.13)';ctx.fillRect(0,0,960,540)}else if(act7Ready){ctx.drawImage(art.act7Square,0,0,art.act7Square.naturalWidth,art.act7Square.naturalHeight,0,0,960,540);ctx.fillStyle='rgba(8,12,16,.12)';ctx.fillRect(0,0,960,540)}else drawSceneArchitecture(game.scene);if(!paintedBackdrop&&game.scene!==1){ctx.fillStyle='#090b0b44';for(let i=0;i<8;i++){let h=72+(i%3)*18;ctx.fillRect(i*140-30,430-h,105,h)}ctx.fillStyle='rgba(25,24,21,.84)';ctx.fillRect(0,430,960,110);ctx.fillStyle='#514a3a';for(let x=0;x<960;x+=70)ctx.fillRect(x,426+(x%140?3:0),46,5)}
 dust.forEach((p,i)=>{p.x=(p.x-p.s+960)%960;ctx.fillStyle=`rgba(204,188,151,${.04+(i%4)*.018})`;ctx.fillRect(p.x,p.y,p.r,p.r)});
 ctx.fillStyle='#d4bd8a99';ctx.font='11px Courier New';ctx.fillText(sc.name.toUpperCase(),28,34);ctx.fillStyle='#d4bd8a44';ctx.fillRect(28,45,130,1);
 sc.objects.forEach(([x,t])=>{if(game.scene===1&&t==='door'){if(!(art.ruinsDoor.complete&&art.ruinsDoor.naturalWidth))drawWoodDoor(x)}else if(game.scene===1&&t==='sign'){}else drawObject(x,t)});if(schoolReady){ctx.save();drawBlackboardWriting();for(let i=0;i<schoolPhotoSpots.length;i++)drawSchoolPhotoFragment(i);drawSchoolAssembledPhoto();ctx.restore()}
 if(game.interact&&!game.locked){let targets=[770,640,(game.scene===2?((game.event&1)?820:440):game.scene===3?((game.event&1)?366:460):520),460,490,760,820],tx=targets[game.scene]||game.x;let pulse=5+Math.sin(Date.now()/170)*2;ctx.strokeStyle='#d7bc7acc';ctx.lineWidth=2;ctx.beginPath();ctx.arc(tx,280,pulse,0,7);ctx.stroke();ctx.fillStyle='#d7bc7a';ctx.beginPath();ctx.moveTo(tx,292);ctx.lineTo(tx-5,284);ctx.lineTo(tx+5,284);ctx.fill()}
 if(game.scene===3){let light=clinicLampLevel();if(light>.02){ctx.save();ctx.globalCompositeOperation='screen';let glow=ctx.createRadialGradient(460,164,6,460,182,435);glow.addColorStop(0,`rgba(255,240,194,${light*.56})`);glow.addColorStop(.34,`rgba(247,221,162,${light*.23})`);glow.addColorStop(1,'rgba(241,219,163,0)');ctx.fillStyle=glow;ctx.fillRect(28,0,864,448);ctx.fillStyle=`rgba(255,241,196,${.48+light*.5})`;ctx.fillRect(453,157,14,10);ctx.restore()}else{ctx.fillStyle='rgba(0,0,0,.32)';ctx.fillRect(0,0,960,430)}}
 if(game.scene===1){drawHe111Shadow(game.plane-270,214,.48,.15);drawHe111Shadow(game.plane-90,262,.72,.25);drawHe111Shadow(game.plane+145,312,1,.43)}
 if(game.scene===7){drawRoom();ctx.restore();drawScreenFX();return}
 ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(game.x,431,22,5,0,0,7);ctx.fill();drawPixelPerson(game.x,440);
 if(game.boss){let bx=game.boss==='chase'?Math.max(-30,game.x-170+game.bossT*.9):game.boss==='shadow'?600:480;ctx.fillStyle=`rgba(5,6,7,${.55+Math.sin(game.bossT/12)*.12})`;ctx.beginPath();ctx.arc(bx,330,110+Math.sin(game.bossT/9)*20,0,7);ctx.fill();for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(bx-90+i*25,400-Math.random()*35,45,0,7);ctx.fill()}}
 game.falling.forEach(p=>{ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot);ctx.fillStyle=p.type===0?'#342c24':p.type===1?'#66513a':'#98866b';ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size*(p.type===1?.55:1));if(p.type===2){ctx.globalAlpha=.35;ctx.fillRect(-2,-p.size*1.4,4,p.size*2.8)}ctx.restore()});game.debris.forEach(d=>{if(d.t<35&&d.t>0){ctx.fillStyle='#a37d4855';ctx.fillRect(d.x-30,420,60,8)}if(d.t<=0&&d.t>-18){ctx.fillStyle='#161512';ctx.fillRect(d.x-14,300+d.t*7+126,28,26);ctx.fillStyle='#a58f6855';for(let i=0;i<7;i++){let spread=(18+d.t)*3;ctx.fillRect(d.x-3+(i-3)*spread/5,410-Math.abs(i-3)*4,6,6)}}});
 if(game.flash>0){ctx.fillStyle='#d8cfb955';ctx.fillRect(0,0,960,540)}ctx.restore();drawScreenFX();if(game.clinicRecord)drawClinicRecord()
}
function drawScreenFX(){if(game.boss){ctx.fillStyle=`rgba(90,105,108,${.025+Math.sin(Date.now()/90)*.018})`;for(let y=0;y<540;y+=7)ctx.fillRect(0,y,960,2)}if(game.fade>0){ctx.fillStyle=`rgba(3,4,4,${Math.min(1,game.fade)})`;ctx.fillRect(0,0,960,540)}if(game.sceneIntro>0&&game.fade<.2){ctx.fillStyle=`rgba(220,203,163,${Math.min(.75,game.sceneIntro/90)})`;ctx.font='18px Georgia';ctx.textAlign='center';ctx.fillText(scenes[game.scene].name,480,100);ctx.textAlign='left'}}
function drawObject(x,t){ctx.save();ctx.translate(x,0);ctx.fillStyle='#332f27';if(t==='table'||t==='desk'){ctx.fillRect(-45,360,90,12);ctx.fillRect(-38,372,8,58);ctx.fillRect(30,372,8,58)}else if(t==='radio'){ctx.fillStyle='#2a2923';ctx.fillRect(-35,348,70,50);ctx.fillStyle='#171816';ctx.fillRect(-28,356,38,34);ctx.strokeStyle='#796647';ctx.strokeRect(-35,348,70,50);ctx.fillStyle='#8c754c';ctx.fillRect(18,357,7,7);ctx.fillRect(18,374,7,7);ctx.strokeStyle='#5f503b';for(let y=362;y<387;y+=6)ctx.strokeRect(-24,y,24,2);ctx.fillStyle=Math.sin(Date.now()/280)>.2?'#c8a35d':'#4b3926';ctx.fillRect(19,387,4,4)}else if(t==='window'||t==='mirror'){ctx.fillRect(-40,220,80,110);ctx.strokeStyle='#8a7654';ctx.strokeRect(-40,220,80,110);if(t==='mirror'&&Math.sin(Date.now()/400)>0.6)drawPixelPerson(0,316,true)}else if(t==='door'||t==='gate'){ctx.fillStyle=t==='gate'?'#27332b':'#2d2922';ctx.fillRect(-35,285,70,145)}else if(t==='sign'){ctx.fillStyle='#516854';ctx.fillRect(-22,330,44,28)}else if(t==='shelf'){for(let y=290;y<420;y+=38)ctx.fillRect(-55,y,110,8)}else if(t==='bread'){ctx.fillStyle='#806542';ctx.fillRect(-18,392,36,15)}else if(t==='drawing'){ctx.fillStyle='#b7a97d';ctx.fillRect(-32,330,64,48)}else if(t==='board'){ctx.fillStyle='#1b2623';ctx.fillRect(-65,255,130,85)}else if(t==='bed'){ctx.fillRect(-65,375,130,22);ctx.fillRect(-60,397,7,33)}else if(t==='lamp'){ctx.fillStyle=Math.sin(Date.now()/330)>.15?'#d8caa588':'#554e3b55';ctx.fillRect(-10,235,20,18);ctx.fillRect(-2,253,4,177)}else if(t==='list'){ctx.fillStyle='#a49a80';ctx.fillRect(-34,295,68,90);ctx.fillStyle='#433f37';for(let y=308;y<374;y+=12)ctx.fillRect(-24,y,48,2)}else if(t==='tunnel'){ctx.fillStyle='#020303';ctx.beginPath();ctx.arc(0,395,60,Math.PI,0);ctx.fillRect(-60,395,120,35);ctx.fill()}else if(t==='luggage'){ctx.fillRect(-24,395,48,35)}else if(t==='clock'){ctx.fillStyle='#171818';ctx.fillRect(-22,185,44,245);ctx.beginPath();ctx.arc(0,180,55,0,7);ctx.fill();ctx.strokeStyle='#887657';ctx.stroke()}ctx.restore()}
function drawRoom(){ctx.fillStyle='#b9ac92';ctx.fillRect(120,80,300,220);ctx.fillStyle='#7c766b';ctx.fillRect(130,90,280,200);ctx.fillStyle='#ddd1b6';ctx.fillRect(140,100,260,180);ctx.fillStyle='#554d40';ctx.fillRect(620,345,110,85);ctx.fillStyle='#34322e';ctx.fillRect(710,330,70,100);drawPixelPerson(675,382,true);ctx.fillStyle='#725f42';ctx.fillRect(520,375,80,10);ctx.fillRect(530,385,8,45);ctx.fillStyle='#292823';ctx.fillRect(542,340,45,32);ctx.fillStyle='#68816d';ctx.fillRect(830,160,55,34);ctx.fillStyle='#d3c49d33';ctx.fillRect(120,300,420,130)}
function update(){if(game.fadeDir===1){game.fade=Math.min(1,game.fade+.055);if(game.fade>=1){game.scene++;game.x=80;game.event=0;updateHUD();game.fadeDir=-1}}else if(game.fadeDir===-1){game.fade=Math.max(0,game.fade-.045);if(game.fade<=0){game.fadeDir=0;game.locked=false;sceneArrival()}}if(game.endingRoom){if(performance.now()-endingRoomStartedAt>=5200){game.endingRoom=false;const done=endingRoomDone;endingRoomDone=null;if(done)done()}draw();requestAnimationFrame(update);return}if(!game.started||game.ending){draw();requestAnimationFrame(update);return}if(game.sceneIntro>0)game.sceneIntro--;if(game.scene===1&&!game.locked&&game.plane<1160){game.plane+=4.4;if(!game.planeSoundPlayed&&game.plane>-120){game.planeSoundPlayed=true;planePassTone()}if(game.plane>465&&game.plane<485&&!game.planeImpact){game.shake=9;game.planeImpact=true}}if(!game.locked&&!game.fadeDir){let sp=game.boss==='chase'?4.2:3,moving=false;if(game.keys.ArrowLeft||game.keys.a){game.x-=sp;game.dir=-1;moving=true}if(game.keys.ArrowRight||game.keys.d){game.x+=sp;game.dir=1;moving=true}if(moving){const now=Date.now();if(now-lastFootstepAt>230){footstepTone();lastFootstepAt=now}}game.x=Math.max(35,Math.min(910,game.x));sceneEvent()}
 game.debris.forEach(d=>{d.t--;if(d.t<1&&d.t>-12&&Math.abs(game.x-d.x)<42)hit()});game.debris=game.debris.filter(d=>d.t>-20);
 if(game.boss){game.bossT++;if(game.boss==='chase'&&game.bossT>60+Math.max(0,40-game.mist*2)&&game.x<780)hit();if(game.boss==='chase'&&game.x>840){game.boss=false;nextScene()}if(game.boss==='storm'&&!game.debris.length){game.boss='shadow';game.bossT=0;say('Fred','That is not a war a child could stop.',()=>{game.locked=false})}if(game.boss==='shadow'){if(game.keys.ArrowLeft||game.keys.ArrowRight||game.keys.a||game.keys.d){if(game.x>880||game.x<40){game.loops++;game.x=480;if(game.loops>=2)ui.prompt.textContent='Stop moving · hold E to face the fog'}}if(game.keys.e&&game.loops>=1){game.bossT++;ui.prompt.classList.remove('hidden');if(game.bossT>170){game.boss=false;ui.prompt.classList.add('hidden');finish()}}else game.bossT=Math.min(game.bossT,110)}}
 game.falling.forEach(p=>{p.y+=p.vy;p.vy+=.12;p.rot+=p.spin});game.falling=game.falling.filter(p=>p.y<452);if(game.flash>0)game.flash--;if(game.shake>0)game.shake=Math.max(0,game.shake-.65);if(game.wobble>0)game.wobble=Math.max(0,game.wobble-.035);draw();requestAnimationFrame(update)}
function finish(){game.scene=7;game.ending=true;updateHUD();startEndingRoomAnimation(()=>startMonologue(endingMonologue,()=>startFilmCredits(endingCredits,returnToTitle),2000))}
const menuText={en:{inspired:'INSPIRED BY',casefile:'CASE FILE',credits:'CODE · PHILIP<br>STORY · RAYNE<br>DESIGN · CHRIS',kicker:'A PIXEL NARRATIVE ABOUT MEMORY',subtitle:'THE LAST BROADCAST',start:'BEGIN MEMORY',hint:'ARROWS / A D MOVE · E INTERACT · MOUSE TO CHOOSE',toggle:'中文'},zh:{inspired:'灵感来源',casefile:'制作档案',credits:'代码 · PHILIP<br>故事 · RAYNE<br>设计 · CHRIS',kicker:'一段关于记忆的像素叙事',subtitle:'最后的广播',start:'开始记忆',hint:'方向键 / A D 移动 · E 互动 · 鼠标选择',toggle:'EN'}};
let menuLang='en';
function applyMenuLanguage(lang){const t=menuText[lang];if(!t)return;menuLang=lang;$('#menuInspired').textContent=t.inspired;$('#menuCasefile').textContent=t.casefile;$('#menuCredits').innerHTML=t.credits;$('#menuKicker').textContent=t.kicker;$('#menuSubtitle').textContent=t.subtitle;$('#startBtn').textContent=t.start;$('#menuHint').textContent=t.hint;$('#languageBtn').textContent=t.toggle;$('#languageBtn').setAttribute('aria-label',lang==='en'?'Switch to Chinese':'切换为英文')}
$('#languageBtn').onclick=()=>applyMenuLanguage(menuLang==='en'?'zh':'en');
document.addEventListener('keydown',e=>{game.keys[e.key]=true;game.keys[e.key.toLowerCase()]=true;if(!ui.filmCredits.classList.contains('hidden')&&(e.key==='e'||e.key==='E'||e.key==='Enter')){e.preventDefault();return}if(e.key===' '&&!ui.filmCredits.classList.contains('hidden')){finishFilmCredits();e.preventDefault();return}if(e.key==='e'||e.key==='E'||e.key==='Enter'){if(!ui.monologue.classList.contains('hidden')){advanceMonologue();e.preventDefault();return}if(game.next)game.next();else if(game.interact&&!game.locked){let action=game.interact;game.interact=null;ui.prompt.classList.add('hidden');action()}}if(['ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault()});document.addEventListener('keyup',e=>{game.keys[e.key]=false;game.keys[e.key.toLowerCase()]=false});$('#mazeListen').onclick=()=>{setMazeMeter(4);$('#mazeCaption').textContent='Listen closely. The ordinary voice is still somewhere ahead.';mazeTone(4)};$('#startBtn').onclick=reset;applyMenuLanguage('en');updateHUD();draw();requestAnimationFrame(update);
